data_path: data
file_extension: h5
dataset_path: ../data/audio_features/
save_model_path: models
debug: False
progress_bar: True
device: cuda:0
num_channels: 1
wandb: False

train:
  mixed_precision: True
  target_sr: 22050
  compress_ratio: 20
  # max_seq_len: [100, 150, 200]
  # Here we adjust the values to the unit of CQT features
  # which are downsampled with a factor of 20 at the time dimension
  max_seq_len: [4400, 6600, 8800]
  num_classes: 10000
  triplet_margin: 0.3
  smooth_factor: 0.1
  model_ckpt: null
  batch_size: 8
  num_workers: 0
  shuffle: True
  drop_last: True
  epochs: 1
  learning_rate: 0.0001
  patience: 4
  tempo_factors: [0.7, 1.3]
  log_steps: 20

val:
  target_sr: 22050
  compress_ratio: 20
  save_val_outputs: True
  max_seq_len: -1
  batch_size: 1
  num_workers: 8
  shuffle: False
  drop_last: False
  output_dir: outputs_val

test:
  target_sr: 22050
  compress_ratio: 20
  save_test_outputs: True
  model_ckpt: null
  max_seq_len: -1
  batch_size: 1
  num_workers: 8
  shuffle: False
  drop_last: False
  output_dir: outputs_test
